USE ClientDW;
GO
INSERT INTO Dimension.Location VALUES 
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('New York', 'NY', 'New York', 10001, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('New York', 'NY', 'New York', 10001, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('New York', 'NY', 'New York', 10001, 'North America'),
   ('New York', 'NY', 'New York', 10001, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('New York', 'NY', 'New York', 10001, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('San Diego', 'CA', 'California', 91911, 'North America'),
   ('Portland', 'OR', 'Oregon', 97035, 'North America'),
   ('Houston', 'TX', 'Texas', 77001, 'North America'),
   ('Denver', 'CO', 'Colorado', 80012, 'North America'),
   ('Miami', 'FL', 'Florida', 33101, 'North America')
;