USE ClientDW;
GO
INSERT INTO Dimension.Customer VALUES 
   ('Joseph', 'Wright', 'Reid, Vega and Merritt'),
   ('Mary', 'Coleman', 'Martinez-Taylor'),
   ('Charles', 'Garcia', 'Perry, Roach and Rivas'),
   ('Steven', 'Pugh', 'Dougherty and Sons'),
   ('Elizabeth', 'Wilson', 'Perez LLC'),
   ('Heidi', 'Jones', 'Jennings, Smith and Brown'),
   ('Kent', 'Grant', 'Day Group'),
   ('Crystal', 'Conner', 'Trujillo, Macias and Thomas'),
   ('Phillip', 'Cruz', 'Torres PLC'),
   ('Joanna', 'Tyler', 'Young, Wood and Scott'),
   ('Ruben', 'Herrera', 'Hall Inc'),
   ('Joyce', 'Jones', 'Horn and Sons'),
   ('Anthony', 'Bartlett', 'Wilkinson PLC'),
   ('Brian', 'Anthony', 'Thomas-Cruz'),
   ('Michael', 'Aguilar', 'Romero-Russell'),
   ('David', 'Flores', 'Kelly-Woods'),
   ('Pamela', 'Robinson', 'Miller, Vasquez and Mcconnell'),
   ('Tonya', 'Powers', 'Cox-Gomez'),
   ('Daniel', 'Duncan', 'Cox, Morrison and Shaw'),
   ('Vincent', 'White', 'Copeland Group'),
   ('Jennifer', 'Murillo', 'Crosby-Miller'),
   ('Kyle', 'Erickson', 'Gray-Harris'),
   ('Brandi', 'Camacho', 'Navarro-Robinson'),
   ('Stephanie', 'Orozco', 'Cabrera, Collins and Nguyen'),
   ('Jennifer', 'Johnson', 'Arnold, Thomas and Pennington'),
   ('Andrea', 'Martin', 'Douglas-Green'),
   ('Lauren', 'Hayden', 'Gray and Sons'),
   ('Nicole', 'Johnson', 'Frederick, Cooper and Acevedo'),
   ('Samantha', 'Stone', 'Garcia, Bailey and Obrien'),
   ('Kevin', 'Robinson', 'Myers, Gill and Wells'),
   ('Cindy', 'Smith', 'Taylor, Smith and Gardner'),
   ('Jordan', 'Hull', 'Alvarez and Sons'),
   ('Kenneth', 'Gross', 'Gonzalez, Villegas and Lee'),
   ('Timothy', 'Richardson', 'Ryan, Oliver and Lutz'),
   ('Oscar', 'Christian', 'Lewis-Davis'),
   ('David', 'Mcknight', 'Williams Group'),
   ('Daniel', 'Martinez', 'Henderson, Murphy and Hartman'),
   ('Marcus', 'Foster', 'Pierce-Lambert'),
   ('Kenneth', 'Hall', 'Griffin Inc'),
   ('Curtis', 'Warren', 'Thompson-Young'),
   ('Robert', 'Grant', 'Snow, Barker and Dean'),
   ('Matthew', 'Pugh', 'Garcia and Sons'),
   ('Jeff', 'Bentley', 'Bowen, Perry and Duran'),
   ('Michael', 'Campbell', 'Martin LLC'),
   ('Brittany', 'Yang', 'Weber and Sons'),
   ('Tyler', 'Oliver', 'Lopez-White'),
   ('Hannah', 'Johnson', 'Pierce-Flynn'),
   ('Lisa', 'Floyd', 'Lewis, Brown and Perez'),
   ('Jennifer', 'Coleman', 'Smith and Sons'),
   ('Laura', 'Sweeney', 'Saunders and Sons')
;