USE ClientDW;
GO
INSERT INTO Dimension.Service VALUES 
   ('Metrics Reporting', 678),
   ('Debt Restructuring', 894),
   ('Debt Restructuring', 377),
   ('Debt Restructuring', 367),
   ('Financial Advisor Services', 131),
   ('Account Managemenet', 13),
   ('Financial Advisor Services', 53),
   ('Financial Advisor Services', 963),
   ('Debt Restructuring', 138),
   ('Financial Advisor Services', 361),
   ('Account Managemenet', 39),
   ('Account Managemenet', 937),
   ('Metrics Reporting', 326),
   ('Financial Advisor Services', 144),
   ('Account Managemenet', 242),
   ('Account Managemenet', 244),
   ('Metrics Reporting', 259),
   ('Debt Restructuring', 660),
   ('Debt Restructuring', 290),
   ('Debt Restructuring', 734),
   ('Metrics Reporting', 866),
   ('Debt Restructuring', 283),
   ('Financial Advisor Services', 479),
   ('Financial Advisor Services', 554),
   ('Debt Restructuring', 484),
   ('Financial Advisor Services', 65),
   ('Metrics Reporting', 81),
   ('Metrics Reporting', 125),
   ('Financial Advisor Services', 87),
   ('Debt Restructuring', 951),
   ('Metrics Reporting', 905),
   ('Metrics Reporting', 777),
   ('Metrics Reporting', 594),
   ('Account Managemenet', 386),
   ('Financial Advisor Services', 77),
   ('Debt Restructuring', 763),
   ('Account Managemenet', 131),
   ('Debt Restructuring', 105),
   ('Debt Restructuring', 778),
   ('Account Managemenet', 544),
   ('Financial Advisor Services', 281),
   ('Metrics Reporting', 448),
   ('Account Managemenet', 388),
   ('Debt Restructuring', 801),
   ('Account Managemenet', 295),
   ('Debt Restructuring', 155),
   ('Metrics Reporting', 959),
   ('Financial Advisor Services', 571),
   ('Financial Advisor Services', 309),
   ('Metrics Reporting', 678)
;